name: learn GA

on: [push]

jobs: 
    run-shell-command: 
      runs-on: ubuntu-latest
      steps: 
        - name: echo a string
          run: eccho "Hello World"
        - name: echo current directory
          run: ls ./
        - name: multiline script
          run: |
            node -v
            npm -v
        